### ISSUE TITLE
VRB model ckpt

### ISSUE THREAD

**Issue by minghaoguo20** [StanfordMSL/Splat-MOVER#2]
I really appreciate your work which is great.
I noticed that you are leveraging the VRB model to get the 2D affordance. 
However, the VRB model download link is broken and the issue in VRB's repo is still open.
I wonder if it's possible for you to share the model ckpt you used?
Thanks a loooooot!

**Comment by shorinwa** [comment]
Hey! The VRB model checkpoint is available [here](https://drive.google.com/drive/folders/1Wz2b1Q-Um_q1IRC1LtCtnvF4gXl2_uwj?usp=sharing). Thanks!
